### ISSUE TITLE
your thing doesn't work at all

### ISSUE THREAD

**Issue by ZGuardianTV** [binaryfox0/W32Calc#1]
![image](https://github.com/Octopus-Computer/W32Calc/assets/89733146/1611c731-5466-475e-b5ec-5f94a1be802f)
"7+7+3 = 10"

**Comment by Octopus-Computer** [comment]
well currently my computer broke so I'm currently coding on phone(i was made it just for fun so it dont too complicated), it like single operand not implement lexer
